### ISSUE TITLE
Shows Listable Bucket but access denied

### ISSUE THREAD

**Issue by random-robbie** [VirtueSecurity/aws-extender#10]
Hi Guys,

I have a bucket that has been listed as being able to read the listings.

[![Screen_Shot_2017-12-12_at_21.17.13.png](https://s33.postimg.org/5ds1z2tlb/Screen_Shot_2017-12-12_at_21.17.13.png)](https://postimg.org/image/6stmnsuob/)

But when i try list the directory it says access denied.

```
root@robbie:~# aws s3 ls s3://coursera_assets

A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied
```

**Comment by 0xSobky** [comment]
Hi @random-robbie,

The bucket is probably readable for authenticated users only, so you need to configure the awscli tool to use your credentials before you try to list the bucket.

This can be done easily by using this command:
`$ aws configure`

Please, let us know if this resolves the problem so we can close this issue.

Thanks!

**Comment by random-robbie** [comment]
Hi Guys,

I had already configured my creds with awscli which is why i am confused as i use the same keys in burp as i do with the awscli

**Comment by 0xSobky** [comment]
Heya @random-robbie,

We believe that the bucket in question was still publicly readable when initially tested. But right after that, the bucket's configurations have been changed so that it's no longer publicly readable. This explains why you have been getting an "AccessDenied" error message from AWS CLI.

Thank you!
